In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Read 16S data

In [3]:
df_16S = pd.read_excel('../data/16S_absolute_abundance.xlsx', index_col=0)
df_16S.head()

,A2,ASF356,Acetatifactor,Acetatifactor-muris,Acidovorax,Acinetobacter,Acinetobacter-sp.-CIP-56.2,Acutalibacter-muris,Adlercreutzia-mucosicola,Adlercreutzia-muris,...,[Eubacterium]-ventriosum-group,[Eubacterium]-xylanophilum-group,[Ruminococcus]-gnavus-group,[Ruminococcus]-torques-group,bacterium-enrichment-culture-clone-M153,gut-metagenome,human-gut-metagenome,marine-metagenome,metagenome,mouse-gut-metagenome
SampleID,,,,,,,,,,,,,,,,,,,,,
sample131,0.0,108301.701888,7101.750943,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,63028.039623,0.0,0.0,0.0,165115.709436,0.0,0.0,0.0,1.322701e+05
sample132,0.0,405068.034693,50064.588558,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,80103.341692,0.0,0.0,0.0,106501.033841,0.0,0.0,0.0,1.003112e+06
sample133,0.0,36169.603950,45332.570284,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.000000,0.0,0.0,0.0,221840.237562,0.0,0.0,0.0,1.866352e+05
sample134,0.0,484302.054587,10150.043060,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,105850.449056,0.0,0.0,0.0,919303.900024,0.0,0.0,0.0,8.714537e+05
sample135,0.0,91489.970533,42374.302141,0.0,0.0,0.0,0.0,0.0,12519.680178,0.0,...,0.0,0.000000,0.0,0.0,0.0,581683.602124,0.0,0.0,0.0,5.335310e+05

# Read meta data

In [4]:
df_meta = pd.read_excel('../data/meta_data.xlsx', index_col=0)
df_meta.head()

          MiceID   Vendor  Day     Diet
SampleID
sample131    BC1  Beijing    0  Control
sample132    BC2  Beijing    0  Control
sample133    BC3  Beijing    0  Control
sample134    BC4  Beijing    0  Control
sample135    BC5  Beijing    0  Control

# Combine data tables

In [7]:
df_16S_meta = pd.merge(df_meta, df_16S, left_index=True, right_index=True, how='inner')
df_16S_meta.head()

,MiceID,Vendor,Day,Diet,A2,ASF356,Acetatifactor,Acetatifactor-muris,Acidovorax,Acinetobacter,...,[Eubacterium]-ventriosum-group,[Eubacterium]-xylanophilum-group,[Ruminococcus]-gnavus-group,[Ruminococcus]-torques-group,bacterium-enrichment-culture-clone-M153,gut-metagenome,human-gut-metagenome,marine-metagenome,metagenome,mouse-gut-metagenome
SampleID,,,,,,,,,,,,,,,,,,,,,
sample131,BC1,Beijing,0,Control,0.0,108301.701888,7101.750943,0.0,0.0,0.0,...,0.0,63028.039623,0.0,0.0,0.0,165115.709436,0.0,0.0,0.0,1.322701e+05
sample132,BC2,Beijing,0,Control,0.0,405068.034693,50064.588558,0.0,0.0,0.0,...,0.0,80103.341692,0.0,0.0,0.0,106501.033841,0.0,0.0,0.0,1.003112e+06
sample133,BC3,Beijing,0,Control,0.0,36169.603950,45332.570284,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,221840.237562,0.0,0.0,0.0,1.866352e+05
sample134,BC4,Beijing,0,Control,0.0,484302.054587,10150.043060,0.0,0.0,0.0,...,0.0,105850.449056,0.0,0.0,0.0,919303.900024,0.0,0.0,0.0,8.714537e+05
sample135,BC5,Beijing,0,Control,0.0,91489.970533,42374.302141,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,581683.602124,0.0,0.0,0.0,5.335310e+05

# Plot

In [10]:
taxa_to_plot = ['Muribaculaceae',
               'Bacteroides-acidifaciens',
               'Faecalibaculum',
               'Bacteroides',
               'Parasutterella',
               'Lachnospiraceae-bacterium-28-4',
               'Parabacteroides-goldsteinii']

In [ ]:
fig, ax = plt.subplots(figsize=(14,14), nrows=len(taxa_to_plot), ncols=4, sharex=True, sharey=False)
Vendor = ['Shanghai','Hunan','Guangdong','Beijing']
for idx_i, b in enumerate(taxa_to_plot):
    for idx_j, v in enumerate(Vendor):
        curr_df = df_16S_meta[(df_16S_meta.Vendor==v) & (df_16S_meta.Diet=='Inulin')]
        sns.lineplot(x='Day',y=b, marker='o', ci=68, data=curr_df, ax=ax[idx_i,idx_j], color='green') # ci=68 correspond to standard error
        if idx_i==0:
            ax[idx_i,idx_j].set_title(v)
            
        max_height = curr_df[b].max()
        exponent = np.floor(np.log10(max_height))
        leading_digit = int(max_height/10**exponent)+1
        max_height = leading_digit*10**exponent
        ax[idx_i,idx_j].set_ylim([-max_height/10,max_height])
        ax[idx_i,idx_j].set_yticks([0,max_height/2,max_height])
    
        if idx_i==0:
            ax[idx_i,idx_j].set_ylim([-0.4e8,4e8])
            ax[idx_i,idx_j].set_yticks([0,2e8,4e8])
        if idx_i==1:
            ax[idx_i,idx_j].set_ylim([-0.3e8,3e8])
            ax[idx_i,idx_j].set_yticks([0,1.5e8,3e8])
        if idx_i==2:
            ax[idx_i,idx_j].set_ylim([-0.6e7,6e7])
            ax[idx_i,idx_j].set_yticks([0,3e7,6e7])
        if idx_i==3:
            ax[idx_i,idx_j].set_ylim([-0.6e7,6e7])
            ax[idx_i,idx_j].set_yticks([0,3e7,6e7])
        if idx_i==4:
            ax[idx_i,idx_j].set_ylim([-0.5e7,5e7])
            ax[idx_i,idx_j].set_yticks([0,2.5e7,5e7])
        if idx_i==5:
            ax[idx_i,idx_j].set_ylim([-0.2e7,2e7])
            ax[idx_i,idx_j].set_yticks([0,1e7,1e7])
        if idx_i==6:
            ax[idx_i,idx_j].set_ylim([-0.3e7,3e7])
            ax[idx_i,idx_j].set_yticks([0,1.5e7,1.5e7])

In [ ]:
plt.rcParams['svg.fonttype'] = 'none'
plt.savefig('taxa_16S_dynamics_lineplot.svg', format='svg')